apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ye6m14qc1-go 
  janus-idp.io/tekton: ye6m14qc1-go
  backstage.io/kubernetes-id: ye6m14qc1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ye6m14qc1-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  